GET http://localhost:5000/api/user/users

###
GET http://localhost:5000/api/user/users/653b1aa0cad90578d2ea33e0

  
###
PUT  http://localhost:5000/api/user/users/653b28aac3a9670afb4668bd HTTP/1.1
Content-Type: application/json
{
    "name": "Sartor",
    "email": "marco@sartor.com",
    "password": "123456",
}
###

DELETE   http://localhost:5000/api/user/users/653ef707c7c1d369f12a4a5b